//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.CustomerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Model")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.CustomerService.Direccion DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.CustomerService.Prestamo[] PrestamoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cliente_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> direccion_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numero_identificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primer_apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primer_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundo_apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundo_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipo_identificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test.CustomerService.Direccion Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test.CustomerService.Prestamo[] Prestamo {
            get {
                return this.PrestamoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrestamoField, value) != true)) {
                    this.PrestamoField = value;
                    this.RaisePropertyChanged("Prestamo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cliente_id {
            get {
                return this.cliente_idField;
            }
            set {
                if ((this.cliente_idField.Equals(value) != true)) {
                    this.cliente_idField = value;
                    this.RaisePropertyChanged("cliente_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> direccion_id {
            get {
                return this.direccion_idField;
            }
            set {
                if ((this.direccion_idField.Equals(value) != true)) {
                    this.direccion_idField = value;
                    this.RaisePropertyChanged("direccion_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numero_identificacion {
            get {
                return this.numero_identificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.numero_identificacionField, value) != true)) {
                    this.numero_identificacionField = value;
                    this.RaisePropertyChanged("numero_identificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string primer_apellido {
            get {
                return this.primer_apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.primer_apellidoField, value) != true)) {
                    this.primer_apellidoField = value;
                    this.RaisePropertyChanged("primer_apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string primer_nombre {
            get {
                return this.primer_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.primer_nombreField, value) != true)) {
                    this.primer_nombreField = value;
                    this.RaisePropertyChanged("primer_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segundo_apellido {
            get {
                return this.segundo_apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.segundo_apellidoField, value) != true)) {
                    this.segundo_apellidoField = value;
                    this.RaisePropertyChanged("segundo_apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segundo_nombre {
            get {
                return this.segundo_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.segundo_nombreField, value) != true)) {
                    this.segundo_nombreField = value;
                    this.RaisePropertyChanged("segundo_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo_identificacion {
            get {
                return this.tipo_identificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_identificacionField, value) != true)) {
                    this.tipo_identificacionField = value;
                    this.RaisePropertyChanged("tipo_identificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Direccion", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Model")]
    [System.SerializableAttribute()]
    public partial class Direccion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.CustomerService.Cliente[] ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int direccion_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test.CustomerService.Cliente[] Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int direccion_id {
            get {
                return this.direccion_idField;
            }
            set {
                if ((this.direccion_idField.Equals(value) != true)) {
                    this.direccion_idField = value;
                    this.RaisePropertyChanged("direccion_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Prestamo", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Model")]
    [System.SerializableAttribute()]
    public partial class Prestamo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.CustomerService.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> cliente_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fecha_finField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fecha_inicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> monto_aprobadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> monto_solicitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> plazo_financiadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int prestamo_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test.CustomerService.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> cliente_id {
            get {
                return this.cliente_idField;
            }
            set {
                if ((this.cliente_idField.Equals(value) != true)) {
                    this.cliente_idField = value;
                    this.RaisePropertyChanged("cliente_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fecha_fin {
            get {
                return this.fecha_finField;
            }
            set {
                if ((this.fecha_finField.Equals(value) != true)) {
                    this.fecha_finField = value;
                    this.RaisePropertyChanged("fecha_fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fecha_inicio {
            get {
                return this.fecha_inicioField;
            }
            set {
                if ((this.fecha_inicioField.Equals(value) != true)) {
                    this.fecha_inicioField = value;
                    this.RaisePropertyChanged("fecha_inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string moneda {
            get {
                return this.monedaField;
            }
            set {
                if ((object.ReferenceEquals(this.monedaField, value) != true)) {
                    this.monedaField = value;
                    this.RaisePropertyChanged("moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> monto_aprobado {
            get {
                return this.monto_aprobadoField;
            }
            set {
                if ((this.monto_aprobadoField.Equals(value) != true)) {
                    this.monto_aprobadoField = value;
                    this.RaisePropertyChanged("monto_aprobado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> monto_solicitado {
            get {
                return this.monto_solicitadoField;
            }
            set {
                if ((this.monto_solicitadoField.Equals(value) != true)) {
                    this.monto_solicitadoField = value;
                    this.RaisePropertyChanged("monto_solicitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> plazo_financiado {
            get {
                return this.plazo_financiadoField;
            }
            set {
                if ((this.plazo_financiadoField.Equals(value) != true)) {
                    this.plazo_financiadoField = value;
                    this.RaisePropertyChanged("plazo_financiado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int prestamo_id {
            get {
                return this.prestamo_idField;
            }
            set {
                if ((this.prestamo_idField.Equals(value) != true)) {
                    this.prestamo_idField = value;
                    this.RaisePropertyChanged("prestamo_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoField, value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerService.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/InsertCliente", ReplyAction="http://tempuri.org/ICustomerService/InsertClienteResponse")]
        int InsertCliente(string numeroIdentificacion, string tipoIdentificacion, string primerNombre, string segundoNombre, string primerApellido, string segundoApellido, string direccion, bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/InsertCliente", ReplyAction="http://tempuri.org/ICustomerService/InsertClienteResponse")]
        System.Threading.Tasks.Task<int> InsertClienteAsync(string numeroIdentificacion, string tipoIdentificacion, string primerNombre, string segundoNombre, string primerApellido, string segundoApellido, string direccion, bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCliente", ReplyAction="http://tempuri.org/ICustomerService/GetClienteResponse")]
        Test.CustomerService.Cliente GetCliente(int clienteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCliente", ReplyAction="http://tempuri.org/ICustomerService/GetClienteResponse")]
        System.Threading.Tasks.Task<Test.CustomerService.Cliente> GetClienteAsync(int clienteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateCliente", ReplyAction="http://tempuri.org/ICustomerService/UpdateClienteResponse")]
        void UpdateCliente(int clienteId, string numeroIdentificacion, string tipoIdentificacion, string primerNombre, string segundoNombre, string primerApellido, string segundoApellido, int direccionId, bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateCliente", ReplyAction="http://tempuri.org/ICustomerService/UpdateClienteResponse")]
        System.Threading.Tasks.Task UpdateClienteAsync(int clienteId, string numeroIdentificacion, string tipoIdentificacion, string primerNombre, string segundoNombre, string primerApellido, string segundoApellido, int direccionId, bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/DeleteCliente", ReplyAction="http://tempuri.org/ICustomerService/DeleteClienteResponse")]
        void DeleteCliente(int clienteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/DeleteCliente", ReplyAction="http://tempuri.org/ICustomerService/DeleteClienteResponse")]
        System.Threading.Tasks.Task DeleteClienteAsync(int clienteId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : Test.CustomerService.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<Test.CustomerService.ICustomerService>, Test.CustomerService.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InsertCliente(string numeroIdentificacion, string tipoIdentificacion, string primerNombre, string segundoNombre, string primerApellido, string segundoApellido, string direccion, bool estado) {
            return base.Channel.InsertCliente(numeroIdentificacion, tipoIdentificacion, primerNombre, segundoNombre, primerApellido, segundoApellido, direccion, estado);
        }
        
        public System.Threading.Tasks.Task<int> InsertClienteAsync(string numeroIdentificacion, string tipoIdentificacion, string primerNombre, string segundoNombre, string primerApellido, string segundoApellido, string direccion, bool estado) {
            return base.Channel.InsertClienteAsync(numeroIdentificacion, tipoIdentificacion, primerNombre, segundoNombre, primerApellido, segundoApellido, direccion, estado);
        }
        
        public Test.CustomerService.Cliente GetCliente(int clienteId) {
            return base.Channel.GetCliente(clienteId);
        }
        
        public System.Threading.Tasks.Task<Test.CustomerService.Cliente> GetClienteAsync(int clienteId) {
            return base.Channel.GetClienteAsync(clienteId);
        }
        
        public void UpdateCliente(int clienteId, string numeroIdentificacion, string tipoIdentificacion, string primerNombre, string segundoNombre, string primerApellido, string segundoApellido, int direccionId, bool estado) {
            base.Channel.UpdateCliente(clienteId, numeroIdentificacion, tipoIdentificacion, primerNombre, segundoNombre, primerApellido, segundoApellido, direccionId, estado);
        }
        
        public System.Threading.Tasks.Task UpdateClienteAsync(int clienteId, string numeroIdentificacion, string tipoIdentificacion, string primerNombre, string segundoNombre, string primerApellido, string segundoApellido, int direccionId, bool estado) {
            return base.Channel.UpdateClienteAsync(clienteId, numeroIdentificacion, tipoIdentificacion, primerNombre, segundoNombre, primerApellido, segundoApellido, direccionId, estado);
        }
        
        public void DeleteCliente(int clienteId) {
            base.Channel.DeleteCliente(clienteId);
        }
        
        public System.Threading.Tasks.Task DeleteClienteAsync(int clienteId) {
            return base.Channel.DeleteClienteAsync(clienteId);
        }
    }
}
